### ISSUE TITLE
Trying to upgrade cqrs sample 

### ISSUE THREAD

**Issue by pawarvijay** [adrai/cqrs-sample#13]
Need Assistance in upgrading cqrs_sample

- I wanted to use your modules . . . and found that existing cqrs_sample is very old . . . so i ended up in upgrading your existing repository but __it din't work__ :>)

- Also i played / debugged your existing cqrs-sample . . . and now want to use latest libraries in production

[link to crqs-sample upgrade that i tried](https://github.com/pawarvijay/cqrs-sample)

__Change List :__
1 : updated cqrs-domain  , cqrs-eventdenormalizer , viewmodel to latest 
2 : corresponding to above 3 core modules i also updated configuration code in server.js
     by referencing to nice documentation in each modules.

__General doubt__
1 : Was It the right way to upgrade your repository( means upgrading module and  configuration code in server.js )
2 : Is it ok to use these modules in production . . or there are major updates yet to come .

__Code doubt__
1 : In domain/server.js file 

*code snippet from [node-cqrs-domain documentation] (https://github.com/adrai/node-cqrs-domain)*

    `domain.onEvent(function (evt, callback) {

         msgbus.emit('event', evt, function ack () {

            callback();
        });

    });`
 
In __msgbus.js__ there is not __emit__ function ..?

2 :  In host/server.js file 

 *code snippet from [node-cqrs-eventdenormalizer documentation] (https://github.com/adrai/node-cqrs-eventdenormalizer)*

     `eventDenormalizer.onEvent(function (evt, callback) {

        msgbus.emit('event', evt, function ack () {

                callback();

            });

        });`
 
In __msgbus.js__ there is not __emit__ function ..?

[link to crqs-sample upgrade that i tried](https://github.com/pawarvijay/cqrs-sample)

**Comment by adrai** [comment]
can you try again... i fixed and updated the dependencies...

**Comment by pawarvijay** [comment]
i tested.its working nicely
