### ISSUE TITLE
on snapshot . mongodb gives some error 

### ISSUE THREAD

**Issue by pawarvijay** [adrai/cqrs-sample#14]
:) I was trying to use snapshot functionality.__Its not producing snapshots__

__configuration that is used for snapshot:__
> snapshotThreshold: 2,  (snapshot after every 2 events)

1 : __on debugging found error in file defultcommandhandler.js : line 370__ 

`
MongoError
key _general.undefined.56710bcd4507c0550bcc1149 must not contain '.'
`

2: __then on further debugging found error here in file aggregateModel.js : line 62__

`
this.get('_revisions')[streamInfo.context + '.' + streamInfo.aggregate + '.' + streamInfo.aggregateId] = rev;
`

*Mongo stores key and values and keys should not contain '.' dott*

am i missing some thing in configuration . . ?

**Comment by adrai** [comment]
i will get a look at it...

**Comment by adrai** [comment]
there was a but... sorry.... cqrs-domain v2.1.0

**Comment by pawarvijay** [comment]
Yesss , snapshots are working now  :+1:
