### ISSUE TITLE
need more understanding on - context: 'context.name',aggregate: 'aggregate.name' - in configuration

### ISSUE THREAD

**Issue by pawarvijay** [adrai/cqrs-sample#16]
Define the event structure in ```denormalizer.defineEvent```

need more understanding on  below lines

 // optional, only makes sense if contexts are defined in the 'domainPath' structure
  ```context: 'context.name',```

  // optional, only makes sense if aggregates with names are defined in the 'domainPath' structure
 ```aggregate: 'aggregate.name',```

Is this configuration about LOGICAL directory structure ?
EXAMPLE :This is what i am trying to say
```javascript
cqrs-example
	domain
		lib
           sales (does this stand for CONTEXT .. ?)
				salesinvocie(does this stand for AGGREGATES .. ?)
					createsalesinvoice.js
					deletesalesinvoice.js
				salesorder
					createsalesorder.js
					deletesalesorder.js
                salesreceipt
					createsalesreceipt.js
					deletesalesreceipt.js
			purchase(does this stand for CONTEXT)
				purchaseorder(does this stand for AGGREGATES)
					createpurchaseorder.js
					deletepurchaseorder.js
				purchasereqisition
					createpurchasereqisition.js
					deletepurchasereqisition.js
````

**Comment by adrai** [comment]
Yes, but you really need a context and aggregate definition file like: https://github.com/adrai/node-cqrs-domain/blob/master/test/integration/fixture/set1/hr/context.js and: https://github.com/adrai/node-cqrs-domain/blob/master/test/integration/fixture/set1/hr/person/aggregate.js

**Comment by pawarvijay** [comment]
1 : do  i also need to structure + configure viewbuilder folder for my context ...?

2 :  i found these references.
 -  configutaion reference :
          from [viewbuilder](https://github.com/adrai/node-cqrs-eventdenormalizer#viewbuilder)
 - folder structure reference : 
    from [viewbuilder testcase](https://github.com/adrai/node-cqrs-eventdenormalizer/tree/master/test/integration/fixture/set1/personDetail)

If Yes , then I short i am trying to know how will i configure viewBuilder for multiple context 
should i use folder structure like

Normally it is like this

```host
	viewBuilders
		item
			collection.js
			itemChanged.js
			itemCreated.js
			itemDeleted.js
```
	
Or 

from [viewbuilder testcase](https://github.com/adrai/node-cqrs-eventdenormalizer/tree/master/test/integration/fixture/set1/personDetail) reference

```
host
	item
		viewbuilders
			itemChanged.js
			itemCreated.js
			itemDeleted.js
		collection.js
	Machine
		viewbuilders
			machineChanged.js
			machineCreated.js
			machineDeleted.js
		collection.js
```

Or according to context manufacturing

```
host
	manufacturing
		item
			viewbuilders
				itemChanged.js
				itemCreated.js
				itemDeleted.js
			collection.js
		Machine
			viewbuilders
				machineChanged.js
				machineCreated.js
				machineDeleted.js
			collection.js
```

**Comment by adrai** [comment]
Viewbuilders are structured by collection (not by context).
Each viewBuilder reacts on an event and denormalizes that event in an appropriate collection.

**Comment by pawarvijay** [comment]
:+1:     
- Above references helped me to understand ,how __cqrs-sample__ can be configured for context ,
- also nice to know Viewbuilders are structured by collection
- this is what i landed up with [ example structured for context  ] (https://github.com/pawarvijay/cqrs-sample/tree/8892d58cad30379cbf8bbfc9e4f66980f2261e3b)  

 __Steps that i followed to implement context__:
1 : Used  configuration like,
     ```context: 'context.name',
     aggregate: 'aggregate.name'    ```
     in 
    ```domain.defineCommand ({   ,
    domain.defineEvent({   ,
    eventDenormalizer.defineEvent({```
2 : structured directory for **context manufacturing** and **aggregate item**
3 : added ```context.js``` according to manufacturing context

Doub't   :>) : 
 - : As i configured for context .While testing , When event is created in eventstore, 
	        It shows ```{ context : '_general' }```.
	_so does it needs to be_ ```{ context : 'manufacturing' }```.
As i have __item__ aggregate inside __manufacturing__ context

Observation :
 - : __readmodel is not generating__ for aggregate

**Comment by pawarvijay** [comment]
my mistake sorry .. my doub't got cleared here i blindly copy pasted  [full file path](https://github.com/pawarvijay/cqrs-sample/commit/309ce6e7ed84d8c1f0ed3857c0dd2d372f93dc34)  from domain test case and now it is clearly showing ```{ context : 'manufacturing' }``` in eventstore

Now testing multiple aggregates in one context then see why readmodel is not generating :)

**Comment by pawarvijay** [comment]
while context is setup,
One  aggregate in one context __works__ and in event store it shows ```{context:'manufacturing'}```
But
two aggregates in one context dosen't and in  event store it shows ```{context:'_general'}```

How did i checked two aggregates dosen't work ..?
initially it was only __item aggregate__ - works nice,
but when i added __machine aggregate__ - it dosen't works.
its not that __machine aggregate__ is having errors,
I INDIVIDUALLY tested both aggregates they work proper.

is there missing any thing ..

**Comment by adrai** [comment]
Do you have this on github? so I can try?

**Comment by adrai** [comment]
ahh didn't see your link, sorry

**Comment by adrai** [comment]
you have not specified de context name in the command message
context.name: https://github.com/pawarvijay/cqrs-sample/blob/master/domain/server.js#L89
the command should have a property context: { name: 'item' } now

**Comment by pawarvijay** [comment]
:)

[i specified context name in the command message and tested](https://github.com/pawarvijay/cqrs-sample/blob/master/host/server.js#L153)

this time it neither generated  event nor revision.

**Comment by adrai** [comment]
can you give me right access to your repo?

**Comment by pawarvijay** [comment]
yes ,  i have added you as collaborator

**Comment by adrai** [comment]
retry ;-)

**Comment by pawarvijay** [comment]
:/ hmm i think some __trail__ mistake from my side.

1 : [when i came to know command should have a property context: { name: 'item' } ](https://github.com/pawarvijay/cqrs-sample/commit/e5311408ce2cb4178add8fb31446765d54f3231f#l3)
__i mistakely coded__     : ```context: { name: 'item' }```,```context: { name: 'machine' }``` 
note : __item__ and __machine__ are not my context
__instead of__ : ```context: { name: 'manufactoring' }```,```context: { name: 'manufactoring' }```
note : __manufactoring__ is my context

2 : @adrai [then you changed lines in configuration](https://github.com/pawarvijay/cqrs-sample/commit/12ad18e5cba73794f7b0ae1de9d86b6b16616d98)
from  : ```context: { name: 'item' }```,```context: { name: 'machine' }```
to:```aggregate: { name: 'item' }```,```aggregate: { name: 'machine' }```

when i tested app with this setup it showed 
```{"context" : "manufactoring"}``` for manufactoring context ,
```{"context" : "sales"}``` for sales context ,
 properly in eventstore
__but but__
when i tested __same aggregate__ in __different context__ they were __not working__

3 : [rectified mistake](https://github.com/pawarvijay/cqrs-sample/blob/master/host/server.js#L155)
i am changing : ```aggregate: { name: 'item' }```,```aggregate: { name: 'machine' }```
to:```context: { name: 'manufactoring' }```,```context: { name: 'sales' }```


when i tested app with this setup it showed 
```{"context" : "manufactoring"}``` for manufactoring context ,
```{"context" : "sales"}``` for sales context ,
 properly in eventstore
Also
when i tested __same aggregate__ in __different context__ they were also __working__ :+1:

**Comment by pawarvijay** [comment]
Also i believe [commit |  little optimization for structureLoader | domain version v2.1.1](https://github.com/adrai/node-cqrs-domain/commit/f187de974bb31a552ed7debc8d7f5de34b008b17) is related to this issue

**Comment by adrai** [comment]
;-)

**Comment by pawarvijay** [comment]
@adrai i think purpose of question is done understanding / implementing context  [example](https://github.com/pawarvijay/cqrs-sample/blob/master/host/server.js#L155) :+1: . And in this example readmodel that is not generating .I will first debug it my self and carry out in next issue

**Comment by pawarvijay** [comment]
Read model generating successfully #17 

[Fully working example :+1: ](https://github.com/pawarvijay/cqrs-sample)
