### ISSUE TITLE
trying to setup saga in cqrs-sample

### ISSUE THREAD

**Issue by pawarvijay** [adrai/cqrs-sample#18]
[cqrs-sample-with-saga](https://github.com/pawarvijay/cqrs-sample-with-saga.git) 

itemCreated.js saga is not responding

doubt's
1 : i am using [onEvent](https://github.com/pawarvijay/cqrs-sample-with-saga/blob/master/saga/server.js#l108) in init function 

is there any thing missing :>)

**Comment by adrai** [comment]
Probably here you have to say false: https://github.com/pawarvijay/cqrs-sample-with-saga/blob/master/saga/lib/itemCreated.js#L15

**Comment by pawarvijay** [comment]
still it [saga](https://github.com/pawarvijay/cqrs-sample-with-saga/blob/master/saga/lib/itemCreated.js#l15) dosen't  responds i think  need to debug :>)

**Comment by adrai** [comment]
DEBUG=* node server.js



Il giorno 15-feb-2016, alle ore 20:59, vijay pawar <notifications@github.com<mailto:notifications@github.com>> ha scritto:


still it saga<https://github.com/pawarvijay/cqrs-sample-with-saga/blob/master/saga/lib/itemCreated.js#l15> dosen't responds i think need to debug :>)

-

**Comment by adrai** [comment]
did you find the issue?

**Comment by pawarvijay** [comment]
yes i found :) ,wait i will post answer in detail

**Comment by pawarvijay** [comment]
it was not issue  , but some wiring mistake from my side

On debugging saga at certain point i found aggregate was undefined so

as i implemented saga in new copy of cqrs-sample repository , 
i did not setup these configurations

`aggregate: 'aggregate.name',` in `domain.defineCommand({ `in Domain folder
`aggregate: 'aggregate.name',` in `domain.defineEvent({`   in Domain folder
`aggregate: 'aggregate.name'`, in `eventDenormalizer.defineEvent({` in Host folder
`aggregate: 'aggregate.name',` in `pm.defineEvent({` in Saga folder
`aggregate : 'item', `in `defineSaga({` in` itemCreated.js saga`

then i almost added all configurations and it worked [example](https://github.com/pawarvijay/cqrs-sample-with-saga)
