### ISSUE TITLE
Best practice in writing tests?

### ISSUE THREAD

**Issue by Jan-Jan** [adrai/cqrs-sample#20]
Hi Adrai,

Thanks a lot for this sample app, and the rest of the cqrs-code -- much appreciated.

I was just wondering if there was a testing best practice that you used? The key testing point for me would be how events are applied to the aggregate. However, the way the code is structured, the callback used to change the aggregate only gets exposed/exported as a `require('cqrs-domain').defineEvent(options, callback)`, which seemingly makes it hard to get to.

**Comment by adrai** [comment]
Thx a lot,
Every of these cqrs modules can be tested like black-box testing.
Every persistence part has an in-memory implementation.
So for example for cqrs-domain you can handlea command and assert the resulting events and even the aggregate data: like -> https://github.com/adrai/node-cqrs-domain/blob/master/test/integration/integrationTest.js#L826
We test everything like that.

**Comment by Jan-Jan** [comment]
Thank you!

**Comment by adrai** [comment]
Bring your aggregate in you "starting position" by handling your commands. Catch the aggregateData of the last handled command.
Then start with your test case and create a diff of the new aggregateData...
btw. my advice is to test your intension (commands/events) not the aggregateData (it's just a temporal in-memory state that helps you enforce your business rules)
