### ISSUE TITLE
[Question] how to do async within defineCommand

### ISSUE THREAD

**Issue by Jan-Jan** [adrai/cqrs-sample#21]
I want to do an async action in the callback of `require('cqrs-domain').defineCommand(options, callback)`. (I want to use bcrypt should by async.) How would one go about it?

Eg,

```
module.exports = require('cqrs-domain').defineCommand({
  name: 'verbNoun'
}, (data, aggregate) => {
  doSomethingAsync(data.value, result => {
    aggregate.apply('nounVerb', result)
  })
})
```

**Comment by adrai** [comment]
Not at all.
Why not sending all information you need in the cmd (message).
So make the async stuff before sending de command to the domain.

**Comment by Jan-Jan** [comment]
Based on @adrai's answer in https://github.com/adrai/node-cqrs-domain/issues/67
I might be able to use the precondition to do something async and add that tot the aggregate. Will report back if I am successful.

**Comment by Jan-Jan** [comment]
Cannot set a value on the aggregate in the precondition step :-(
So back to square one...

**Comment by adrai** [comment]
Manipulating the aggragate is only possible in the defineEvent handler
