### ISSUE TITLE
Error while trying to change inMemory eventStore to mongodb

### ISSUE THREAD

**Issue by dkt201474** [adrai/cqrs-sample#26]
Hi @adrai , 
Thank you for your sample,

I don't know if mongodb has changed it's "connect" function interface, but when I change the type of eventStore from "inMemory" to "mongodb", I get the following error: 

_**.../node_modules/mongodb/lib/mongo_client.js:241
    throw new TypeError('`connect` only accepts a callback')**;_

I'm using mongodb in local.

**Comment by adrai** [comment]
Will look at it later...
Just saw they released a new major version: https://github.com/mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md
Can you try with mongodb 2.x ?

**Comment by dkt201474** [comment]
Same thing with mongoDB version: 2.6.2

**Comment by adrai** [comment]
I updated all cqrs modules, now it should work

**Comment by dkt201474** [comment]
Yes it works perfectly now. Thank you for the quick replies.
